### ISSUE TITLE
Should be able to trigger Views lifecycle events also if just a subview updates

### ISSUE THREAD

**Issue by grosmar** [MVCoconut/coconut.ui#15]
If I have a @:state or @:attr in a View class and it's only consumed by a subelement, then there are no lifecycles fired in my View class, however maybe I want to do some computation based on them.

The only hack I found so far, to reference these properties in the beginning of the render() function, but it's not really nice.

**Comment by back2dos** [comment]
You can now [declare states and attributes as tracked](https://github.com/MVCoconut/coconut.ui/tree/f902e3f0fd1c141ca4231866b593c9b536639d83#tracked-states-and-attributes)
