### ISSUE TITLE
DCE doesn't eliminate unused attributes

### ISSUE THREAD

**Issue by grosmar** [MVCoconut/coconut.ui#16]
Looks like now all my application sizes grow extremely since latest version of coconut.
I looked into the generated js and it looks like if I have attributes that I never use DCE doesn't remove them anymore.

And because I still use `var attributes:Attr` a lot, it generates a lot of code.

**Comment by back2dos** [comment]
I don't quite see what can be done here. If you define dozens of attributes in your public API that are then actually rendered into the DOM, they are being used and DCE acts accordingly.
