### ISSUE TITLE
var attributes:vdom.Attr looks like memory leaking

### ISSUE THREAD

**Issue by grosmar** [MVCoconut/coconut.ui#17]
Based on a few hours of playing around I think `var attributes:vdom.Arr` causes memory leaking. 
I could not figure out so far which porperty causes the leaking, or maybe the full object is leaking just it's visible because vdom.Attr is a huge object.

**Comment by back2dos** [comment]
Hmm. I'm inclined to guess that actually the JS runtime is simply growing the heap to avoid too many GC pauses.
