### ISSUE TITLE
Null reference?

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.ui#18]
<img width="599" alt="screen shot 2018-03-03 at 10 57 18 am" src="https://user-images.githubusercontent.com/1103788/36929871-f4efa3ca-1ed1-11e8-8b02-7f9592c19d12.png">

see the `get_value(null)`, I think it is wrong?

**Comment by kevinresol** [comment]
I need to explicitly annotate the type on [this line](https://github.com/MVCoconut/coconut.ui/blob/300a524/src/coconut/ui/tools/Slot.hx#L30):
```haxe
if (data == (null:Observable<T>))
```

**Comment by back2dos** [comment]
Does updating tink_state help?

**Comment by kevinresol** [comment]
Didn't when I filed the issue. I think I updated every possible dependencies

**Comment by kevinresol** [comment]
I'm on haxe 3.4, is that the problem?

**Comment by back2dos** [comment]
Nope, shouldn't be. The problem is with `==` for observables ... I thought I had finally gotten it right ^^

**Comment by back2dos** [comment]
Ok, this is *really* weird. This test passed just fine: https://github.com/haxetink/tink_state/blob/40fa67ff3f977c564bea6c162536568947eee655/tests/TestBasic.hx#L114

Anyway, it's fixed here for now, until I figure out what to really do about it: https://github.com/haxetink/tink_state/commit/2bda07e49613672842223f45cb7073cfc7799ff4

**Comment by kevinresol** [comment]
Yeah when i tested the equality statement for observables in a separate project it works fine. 

Do you get the same generated code as mine in the Slot class?

**Comment by back2dos** [comment]
Yup, same code, same error. Strange things happening ^^

**Comment by back2dos** [comment]
Is this still a thing?

**Comment by kevinresol** [comment]
Let's assume it is gone
