### ISSUE TITLE
@:attr var attr:Dynamic; crashes

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.ui#20]
I think some implicit casts failed. Treating the `Dynamic` as an observable itself.

**Comment by back2dos** [comment]
Well, getting this to work might be quite tricky. Do you need it? Otherwise I'm inclined to make it a compiler time error for the time being.

**Comment by kevinresol** [comment]
I don't really need it. Just happen to encounter this while quick prototyping.

**Comment by back2dos** [comment]
For now this is forbidden.
