### ISSUE TITLE
Docs needed

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.ui#21]
I will try to consolidate some topics that I think requires documentation/explanations. Some may belong to tink_hxx or specific renderer, but I am not sure:

- [x] **rendering-function vs full `View` class**: performance, caching, allows state, etc
- [x] **attribute-declared-as-children syntax**: `<Parent><attr1 props><Child {...props}/></attr1></Parent>`
- [ ] **attribute name mangling**: e.g. `class -> className`
- [x] **typing function attributes**: `<div onclick={attr = value}/>` <- this works somehow, but the haxe expr is not a function at all
- [ ] **observable vs plain value**: e.g. `function render() '<div attr={value}/>'`, what is the difference if `value` is Observable vs a plain value?
- [x] **view caching**: how it works?

Feel free to add to the list.

**Comment by gene-pavlovsky** [comment]
If I may add, `tink_hxx` docs:
- Interpolation ... "either by using JSX like syntax or by using Haxe interpolation syntax" - some reference and/or examples of what is "JSX like syntax"
- Spread ... "HXX has the capacity to deal with spreads, e.g. <someTag {...properties} />" - after a conversation with @back2dos I see this is a huge topic, deserving more details and examples on the possibilities
- If an `@:attribute var children:Children` is defined in a view, child nodes end up there. I couldn't find a mentiond of that in the doc

**Comment by back2dos** [comment]
Most of this is documented now. The rest is pretty backend specific.
