### ISSUE TITLE
[gen4] type errors are mutated to something weird

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.ui#33]
```haxe
// Main.hx
class Main extends coconut.ui.View {
  static function main() {}
  function render() '<Foo/>';
}

// Foo.hx
class Foo extends coconut.ui.View {
	function render() '<div/>';
	function capture(e:Dummy) {}
}
```

Expected: `Type not found : Dummy`
Actual: `this direct initialization causes the compiler to do really weird things`

**Comment by back2dos** [comment]
After banging my head against this for a while I must accept defeat.

The basic problem seems to be that when `Foo` is first accessed during expression typing (i.e. the body of `Main::render`) the whole class winds up empty (no fields - at least when you query the compiler for them from macros). I did try make hxx just generate `null` for tags referring to classes that look broken in this way. Then I get `Unknown identifier : hxx` in `Foo::render`, so even `Foo`'s relationship with its super class seems broken. 

The best I could do right now is to detect that typing went wrong and report an error that suggests either importing the class before usage (adding `import Foo;` in `Main` results in the correct error) or compiling the type separately.

**Comment by back2dos** [comment]
Need to make a small reproducible sample and raise a Haxe issue.

**Comment by kevinresol** [comment]
Can't reproduce anymore with rc3 and latest libraries.
