### ISSUE TITLE
VSHaxe code completion issue

### ISSUE THREAD

**Issue by Grabli66** [MVCoconut/coconut.ui#36]
I found a bug, but i don't know it's bug of VSHaxe or bug of coconut.ui (tink_*, etc). 
It appears only when i use latest coconut.ui from git and latest tink libs from git.

Source code:
```haxe
import js.Browser.*;

class Main {
	public static function main() {
		coconut.ui.Renderer.mount(document.body, new App({}));
	}
}

class App extends coconut.ui.View {
	var name:String;

	function render() {
		return hxx('<div>GOOD</div>');
	}
}
```

When i hover on any item in class that extends coconut.ui.View, it shows "@:optional ..."
![screen2](https://user-images.githubusercontent.com/8269676/51736307-c691b100-209a-11e9-976e-881c013c8560.png)

build.hxml
-cp src
-main Main
-lib coconut.ui
-lib coconut.vdom
-js out/main.js

Haxe Compiler 4.0.0-preview.5+da718a30e 
Windows 7 x64

**Comment by back2dos** [comment]
Latest head should improve this.

**Comment by Grabli66** [comment]
Latest version works. Thanks.
