### ISSUE TITLE
integration with deepstate

### ISSUE THREAD

**Issue by francescoagati** [MVCoconut/coconut.ui#39]
hi,
there is an example of integration of coconut with deepstate?

**Comment by kevinresol** [comment]
coconut.data is the official stateful data store and is preferred I suppose. Do you have a reason to not use it and go for deepstate?

**Comment by francescoagati** [comment]
i have a project that use deepstate but i want move the ui to coconut  for future scalability on other renderers

**Comment by back2dos** [comment]
As far as I understand it, the data is in a `DeepStateContainer<T>` and you can make it observable like so:

```haxe
function tinkify<T>(container:DeepStateContainer<T>) {
  var state = new tink.state.State(container.state);
  container.subscribeObserver(Full(function (prev, next) state.set(next));//make sure it's prev and next and not next and prev
  return state.observe();
}
```

And as soon as you have an observable, you can pass it to coconut and it will update. I'm a bit worried about the performance implications here, but it should work correctly. Perhaps you also want to create "enclosures" as you pass data down.

All that said, coconut.ui is literally **built on top of** coconut.data, so gluing in another, radically different state layer is going to require a fair amount of work and the result will probably still be awkward. If you just want different renderers, then that's where you should be putting your energy.

I'm going to close this issue, but please feel free to follow up with questions you run into if you go down this road ;)

**Comment by francescoagati** [comment]
thanks @back2dos  i will try tinfiy deepstate for see what happens.
