### ISSUE TITLE
Root level switch case

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.ui#4]
Is it possible to make this work?

```haxe
import coconut.data.*;
import coconut.ui.*;
import coconut.Ui.*;

class Main {
    static function main() {
        var h = hxx('<MyView />');
        var e = h.toElement();
        trace(h);
        trace(e); // null
        js.Browser.document.body.appendChild(e);
    }
}

class MyView extends View<{}> {
    function render() '
        <switch ${int()}>
            <case ${0}>
                <div>Zero</div>
            <case ${1}>
                <div>One</div>
            <case ${_}>
                <div>Default</div>
        </switch>
    ';
    
    function int() return 1;
}
```

**Comment by back2dos** [comment]
This is surprisingly tricky, because a `case` can have multiple children, so the result of it is going to be an array and virtual-dom seems to choke on that. In any case, the code should either work or not compile ^^

**Comment by kevinresol** [comment]
I am thinking if it is possible to do it like this:

If the root is a control structure, then the cases must be returning a single node.

But I am not sure if it will cause problems if the root node is mutable. If it is too messy, feel free to close.

**Comment by back2dos** [comment]
If I'm not mistaken the gen2 stuff actually allows for this. At least it's it's written in a way that should make this possible.

**Comment by back2dos** [comment]
Tests confirm that this works now.
