### ISSUE TITLE
Multiple backends

### ISSUE THREAD

**Issue by markknol** [MVCoconut/coconut.ui#42]
> Me:  I was wondering, is it possible to have multiple renderers in the same build. eg. lets say I want half of the app coconut.vdom and the other half coconut.pixi or something?
> You: No 

... 

> Me: you mean not at all, I mean also not when there are separate roots?
> You: the problem is that currently, there are types such as RenderResult which tend to be quite useful, but if you want to have multiple backends, that won't fly
> You: for me it's not that hard, but presenting a nice api to the user will be tricky ^^
you'll have to write `extends View<js.html.Node>` and `extends View<pixijs.Sprite>` and what not
> Me: 💡 yeah or `extends coconut.vdom.View` and `extends coconut.pixi.View`. but I understand this is tricky and opens box of lesser nice api
> You: 💡 actually, that's pretty cool
> You:  can you please dump that in a ticker for me?

There you go! 🚀

**Comment by back2dos** [comment]
Works with current HEAD.

**Comment by markknol** [comment]
> Me: 💡 actually, that's pretty cool
