### ISSUE TITLE
Feature request: have default children for view classes also

### ISSUE THREAD

**Issue by grosmar** [MVCoconut/coconut.ui#9]
Right now if you have a coconut view then it's impossible to have default children, and you always have to specify it. If you create View classes that are used as containers many times it would be convinient to just define the children directly.

ie using hxx:
```
<List>
    <ListItem>hello1</ListItem>
    <ListItem>hello2</ListItem>
    <ListItem>hello3</ListItem>
</List>
```

**Comment by back2dos** [comment]
Works now.
